# Generated by Django 3.2.3 on 2021-05-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210528_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtitle',
            old_name='description',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='description',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='workgroup',
            old_name='description',
            new_name='name',
        ),
    ]
