# Generated by Django 3.2.3 on 2021-06-01 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210601_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transformer',
            old_name='dessocantColor',
            new_name='dessicantColor',
        ),
    ]
