# Generated by Django 3.2.3 on 2021-06-03 22:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210603_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitSwitcher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('counter', models.IntegerField(null=True)),
                ('operatorGoodCond', models.BooleanField(null=True)),
                ('gasPressProperPress', models.BooleanField(null=True)),
                ('controlCabGoodCond', models.BooleanField(null=True)),
                ('standGoodCond', models.BooleanField(null=True)),
                ('interrupterCond', models.CharField(max_length=25, null=True)),
                ('insulatorFreeLeak', models.BooleanField(null=True)),
                ('disconnectSwitchGoodCond', models.BooleanField(null=True)),
                ('equipmentLabelProp', models.BooleanField(null=True)),
                ('overallEquipCond', models.CharField(max_length=25, null=True)),
                ('foundationGoodCond', models.BooleanField(null=True)),
                ('paintCond', models.CharField(max_length=50, null=True)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.equipment', verbose_name='Equipment')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inspection', verbose_name='Inspection')),
            ],
        ),
    ]
