# Generated by Django 3.2.3 on 2021-06-03 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company', verbose_name='Company'),
        ),
    ]
