# Generated by Django 3.2.3 on 2021-06-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210604_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
