# Generated by Django 3.2.3 on 2021-06-04 22:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_inspection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='name',
            field=models.CharField(default=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False), max_length=100),
        ),
    ]
