# Generated by Django 3.2.3 on 2021-06-04 22:58

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_inspection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='name',
            field=models.CharField(default=django.db.models.fields.Field.value_to_string, max_length=100),
        ),
    ]
