# Generated by Django 3.2.3 on 2021-06-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_inspection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='name',
            field=models.CharField(default='<django.db.models.fields.UUIDField>', max_length=100),
        ),
    ]
